#!/usr/bin/env bash

clr_cache() {
    if [[ -d "$REAL_HOME/.cache/yay" ]]; then
        step "Limpando builds do AUR..."
        find "$REAL_HOME/.cache/yay" -maxdepth 1 -type d -not -path "$REAL_HOME/.cache/yay" -exec rm -rf {} +
        echo -e "${GREEN} $COMPLETE ${NC}"
    fi
    if command -v flatpak &>/dev/null; then
        step "Limpando sobra de Flatpaks..."
        flatpak uninstall --unused -y &>/dev/null
        echo -e "${GREEN} $COMPLETE ${NC}"
    fi

    step "Limpando cache do pacman..."
    CMD="-Scc"
    TAG="CLEANED CACHE"
}

remove_orphans() {
    step "Buscando pacotes orfãos..."
    ORPHANS="$(yay -Qtqd)"
    ORPHANS_N="$(yay -Qtqd | wc -l)"
    [[ "$ORPHANS_N" == "0" ]] && success "Nenhum pacote orfão encontrado" && logger "[SEARCHED ORPHANS]" "clean" && exit 0
    echo "$NOTE $ORPHANS_N Orfãos encontrados"
    echo "$ORPHANS"
    step "Removendo Orfãos..."
    CMD="-Rsn $ORPHANS"
    TAG="REMOVED ORPHANS"
}

check_conf() {
    step "Buscando arquivos .pacnew/.pacsave..."
    PACNEWS=$(find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2>/dev/null)

    if [[ -z "$PACNEWS" ]]; then
        success "Tudo limpo! Nenhum conflito em /etc."
    else
        echo -e "${YELLOW} $NOTE Arquivos pendentes encontrados:${NC}"
        echo "$PACNEWS"
        echo -e "\n${CYAN} $CC ${NC}Mesclar agora com pacdiff? [y/N]"
        read -r -n 1 opt
        echo
        if [[ "$opt" =~ ^(y|Y)$ ]]; then
            sudo pacdiff
        fi
    fi
    TAG="CLEAR DIFFS"
}