#!/usr/bin/env bash

clr_cache() {
    if [[ -d "$REAL_HOME/.cache/yay" ]]; then
        step "Cleaning AUR builds..."
        find "$REAL_HOME/.cache/yay" -maxdepth 1 -type d \
        -not -path "$REAL_HOME/.cache/yay" -exec rm -rf {} +
        success "Builds cleaned."
    fi
    if command -v flatpak &>/dev/null; then
        step "Cleaning unused Flatpaks..."
        flatpak uninstall --unused -y &>/dev/null
        success "Flatpaks cleaned."
    fi
    step "Cleaning pacman cache..."
    CMD="-Scc"
    TAG="CLEANED CACHE"
}

remove_orphans() {
    step "Searching for orphan packages..."
    mapfile -t FINAL_ARGS < <(yay -Qqtd 2>/dev/null)
    ORPHANS_N=${#FINAL_ARGS[@]}
    if [[ "$ORPHANS_N" -eq 0 ]]; then
        success "No orphan packages found"
        logger "SEARCHED ORPHANS" "clean"
        exit 0
    fi
    echo "$NOTE $ORPHANS_N Orphans found"
    printf '%s\n' "${FINAL_ARGS[@]}"
    step "Removing orphans..."
    CMD="-Rsn"
    TAG="REMOVED ORPHANS"
}

check_conf() {
    step "Searching for .pacnew/.pacsave files..."
    PACNEWS=$(find /etc -regextype posix-extended \
    -regex ".+\.pac(new|save)" 2>/dev/null)
    if [[ -z "$PACNEWS" ]]; then
        success "All clear! No conflicts found in /etc."
    else
        echo -e "${YELLOW} $NOTE Pending files found:${NC}"
        echo "$PACNEWS"
        echo -e "\n${CYAN} $CC ${NC}Merge now with pacdiff? [y/N]"
        read -r -n 1 opt
        echo
        [[ "$opt" =~ ^(y|Y)$ ]] && sudo pacdiff
    fi
    TAG="CLEAR DIFFS"
}