#!/usr/bin/env bash

list_aur() {
    step "Filtrando pacotes instalados via AUR..."
    pacman -Qm | column -t
    TAG="[LOCAL_QUERY (AUR)]"
    local count=$(yay -Qm | wc -l)
    echo -e "\n${GREEN}$OK${NC} Total de $count pacotes AUR encontrados."
}
refresh_mirrors() {
    tester
    echo "$WARNING Procurando mirrors..."
    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    sudo reflector --country Brazil --latest 10 --sort rate --save /etc/pacman.d/mirrorlist
    echo "$OK Mirrors atualizados"
    exit 0
}