#!/usr/bin/env bash

show_logs() {
    [[ ! -s "$LOG_FILE" ]] && echo "$NOTE O Arquivo de log está vazio" && exit 0
    column -t -s '|' "$LOG_FILE"
    exit 0
}

clear_logs() {
    > "$LOG_FILE"
    echo "$COMPLETE Arquivo de log limpo"
    exit 0
}