#!/usr/bin/env bash

logger() {
    local status="${EXIT_CODE:-0}"
    local tag="$1"
    local info="$2"
    printf -v date_str '%(%Y-%m-%d - %H:%M:%S)T' -1
    echo "[$date_str] [EXIT STATUS $status] [$tag] -> $info" >> "$LOG_FILE"
}

log_acts() {
    case "$LOG_FUNC" in
        "sl")
            [[ ! -s "$LOG_FILE" ]] && echo "$NOTE The log file is empty." && exit 0
            cat "$LOG_FILE"
            exit 0
        ;;
        "cl")
            > "$LOG_FILE"
            echo "$COMPLETE Cleared log file"
            exit 0
        ;;
    esac
}
