#!/usr/bin/env bash

searcher() {
    tester
    CMD="-Ss"
    TAG="SEARCHED"
    FLAT_CMD="search"
}

query() {
    CMD="-Qs"
    TAG="LOCAL QUERY"
    [[ "$LIST_AUR" == true ]] && list_aur && TAG="SKIP" && return
    [[ "$PTBIN" == true ]] && get_package_path "${FINAL_ARGS[@]}" && TAG="SKIP" && return
}

check_updates() {
    tester
    step "Searching for updates..."
    raw_upds=$(checkupdates 2>/dev/null)
    raw_aur=$(yay -Qua 2>/dev/null)
    [[ -n "$raw_upds" ]] && UPDS_N=$(echo "$raw_upds" | grep -c .) || UPDS_N=0
    [[ -n "$raw_aur" ]] && UPDS_AUR_N=$(echo "$raw_aur" | grep -c .) || UPDS_AUR_N=0
    if [[ "$UPDS_N" -eq 0 && "$UPDS_AUR_N" -eq 0 ]]; then
        success "nothing to do."
        logger "NO UPDATES FOUND" "$((UPDS_N + UPDS_AUR_N)) updates ($UPDS_AUR_N in AUR)"
        exit 0
    fi
    echo -e "${YELLOW} $NOTE $((UPDS_N + UPDS_AUR_N)) Updates found ($UPDS_AUR_N in AUR):${NC}"
    [[ "$UPDS_N" -gt 0 ]] && echo -e "${CYAN}$raw_upds ${NC}"
    [[ "$UPDS_AUR_N" -gt 0 ]] && echo -e "${GREEN}$raw_aur ${NC}"
    logger "FOUND UPDATES" "$((UPDS_N + UPDS_AUR_N)) updates ($UPDS_AUR_N in AUR)"
}

get_package_path() {
    local pkg="$1"
    [[ -z "$pkg" ]] && echo "$ALERT Provide a package name." && exit 1
    if pacman -Qi "$pkg" &>/dev/null; then
        step "Files for package: ${pkg}"
        local bins=$(pacman -Ql "$pkg" | grep '/bin/' | cut -d' ' -f2-)
        if [[ -n "$bins" ]]; then
            echo -e "${GREEN}Binaries found:${NC}"
            echo "$bins"
        else
            echo -e "${YELLOW}No binaries found. Displaying all files instead:${NC}"
            pacman -Ql "$pkg" | cut -d' ' -f2- | less
        fi
        logger "PATH SEARCH" "$pkg"
    else
        logger "PATH SEARCH FAILED" "$pkg"
        echo "$ALERT Package '$pkg' is not installed."; exit 1
    fi
}