#!/usr/bin/env bash

searcher() {
    tester
    CMD="-Ss"
    TAG="SEARCHED"
    FLAT_CMD="search"
}

query() {
    CMD="-Qs"
    TAG="LOCAL QUERY"
    [[ "$LIST_AUR" == true ]] && list_aur && TAG="SKIP" && return
}

check_updates() {
    tester
    step "Searching for updates..."
    UPDS="$(checkupdates 2>/dev/null)"
    UPDS_N="$(echo "$UPDS" | grep -c .)"
    UPDS_AUR="$(yay -Qua 2>/dev/null)"
    UPDS_AUR_N="$(echo "$UPDS_AUR" | grep -c .)"
    if [[ "$UPDS_N" == "0" ]] && [[ "$UPDS_AUR_N" == 0 ]]; then
        success "0 Updates found."
        exit 0
    fi
    echo -e "${YELLOW} $NOTE $UPDS_N Updates found ($AUR_UPDS_N in AUR):${NC}"
    echo "$UPDS"
    echo "$UPDS_AUR"
    logger "FOUND UPDATES" "$UPDS_N updates ($UPDS_AUR_N in AUR)"
}
