#!/usr/bin/env bash

# ~/.config/jay/config

## Always use flatpak in commands
USE_FLATPAK=true

## Always use aggressive mode (-Rsn) in remove command
AGGRESSIVE_MODE=false

## Always use --noconfirm flag in yay commands (use with caution)
USE_NOCONFIRM=false

## network tester timeout
NETWORK_TIMEOUT=1

## enable/disable log
ENABLE_LOG=true

## period in days to clear log file
LOG_CLEAN_PERIOD=7